# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "xuhengzhang"
repo_name: "my-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    # --------- Core Technologies ---------
    "VLA":
        filters: ["Vision Language Action", "Vision-Language-Action", "Vision Language Action Model", "VLA", "Embodied AI"]
    
    "Long-horizon Planning":
        filters: ["Long-horizon", "Long-term Planning", "Task Planning", "Hierarchical Planning", "Sequential Planning", "Multi-step Planning"]
    
    "Open Vocabulary Robotics":
        filters: ["Open Vocabulary", "Open-vocabulary", "Zero-shot Robot", "Generalization", "Open-ended Task"]
    
    # --------- Reasoning & Planning ---------
    "Robot Reasoning":
        filters: ["Robot Reasoning", "Robotic Reasoning", "Spatial Reasoning", "Temporal Reasoning", "Causal Reasoning"]
    
    "Subtask Decomposition":
        filters: ["Task Decomposition", "Subtask", "Sub-task", "Task Segmentation", "Skill Composition"]

    # --------- Memory & History ---------
    "Robot Memory":
        filters: ["Robot Memory", "Episodic Memory", "Working Memory", "Memory-augmented", "Historical Information", "Past Experience"]

    "Temporal Understanding":
        filters: ["Temporal Reasoning", "Sequential Understanding", "History-aware", "Context Memory", "Long-term Memory"]

    # --------- Datasets & Training ---------
    "Robot Datasets":
        filters: ["Robot Dataset", "Robotic Dataset", "Manipulation Dataset", "Robot Data", "Open Dataset"]
    
    "Multi-task Learning":
        filters: ["Multi-task Robot", "Multi-task Learning", "Transfer Learning", "Domain Adaptation", "Cross-task"]
    
    # --------- Foundation Models ---------
    "Robot Foundation Models":
        filters: ["Robot Foundation Model", "Robotic Foundation Model", "General Purpose Robot", "Universal Robot"]
    
    "Vision Language Models":
        filters: ["Vision Language Model", "VLM", "Vision-Language Model", "Multi-modal LLM", "MLLM"]
